# Generated by Django 4.2.6 on 2023-10-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cerere_de_finantare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numele_solicitantului', models.CharField(max_length=255)),
                ('titlul_proiectului', models.TextField()),
                ('programe', models.CharField(choices=[(1, 'Cultura'), (2, 'Mass Media'), (3, 'Educatie'), (4, 'Spiritualitate si Traditie'), (5, 'Societate Civila')], max_length=30)),
                ('locul_derulare', models.TextField(help_text='Adresa, cod postal, Regiune, Localitate, Tara')),
                ('perioada_incepere', models.DateTimeField()),
                ('perioada_incheiere', models.DateField()),
            ],
            options={
                'db_table': 'Cerere_de_Finantare',
            },
        ),
        migrations.CreateModel(
            name='Programe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
