# Generated by Django 4.2.6 on 2023-10-07 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cerere_de_finantare',
            name='perioada_incepere',
        ),
        migrations.RemoveField(
            model_name='cerere_de_finantare',
            name='perioada_incheiere',
        ),
    ]
