# Generated by Django 4.2.7 on 2023-11-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0008_delete_programe_alter_cerere_de_finantare_programe'),
    ]

    operations = [
        migrations.AddField(
            model_name='cerere_de_finantare',
            name='perioada_incepere',
            field=models.DateTimeField(default='20231117'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cerere_de_finantare',
            name='perioada_incheiere',
            field=models.DateField(default='20231117'),
            preserve_default=False,
        ),
    ]
