# Generated by Django 4.2.7 on 2023-11-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0010_alter_cerere_de_finantare_perioada_incepere'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='user_uploads/'),
        ),
    ]
