# Generated by Django 4.2.6 on 2023-11-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0011_userprofile_uploaded_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sesiune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
    ]
