# Generated by Django 4.2.6 on 2023-11-17 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0012_sesiune'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cerere_de_finantare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbapp.cerere_de_finantare'),
        ),
    ]
