# Generated by Django 4.2.6 on 2023-11-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0013_userprofile_cerere_de_finantare'),
    ]

    operations = [
        migrations.AddField(
            model_name='cerere_de_finantare',
            name='descriere',
            field=models.TextField(default=0, help_text='Descrieti proiectul'),
            preserve_default=False,
        ),
    ]
